name: Lint and format

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
          python-version: '3.10'

    - name: Changed files
      id: changed_files
      uses: tj-actions/changed-files@v44

    - uses: pre-commit/action@v3.0.1
      with:
        extra_args: --files ${{ steps.changed_files.outputs.all_changed_files }}
